<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Je suis la !')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no') ?>

        <!-- Le styles -->
        <?php echo $this->headLink()->prependStylesheet('http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile('https://maps.googleapis.com/maps/api/js?key=AIzaSyCXrYix2NHdjG9LwxXIXyKQ-tQ0kgi8G2A&sensor=true')
                                      ->prependFile('http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.js')
                                      ->prependFile('http://code.jquery.com/jquery-1.8.2.min.js') ?>

    </head>
    <body>
         <?php echo $this->content; ?>
    </body>
</html>
