<!-- <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCXrYix2NHdjG9LwxXIXyKQ-tQ0kgi8G2A&sensor=true" type="text/javascript"></script> -->
<script>
function MAP_initialize() {
    console.log("MAP_initialize - START");
  var mapOptions = {
    zoom: 8,
    center: new google.maps.LatLng(-34.397, 150.644),
    mapTypeId: google.maps.MapTypeId.ROADMAP
  }
  var map = new google.maps.Map(document.getElementById("idMapCanvas"), mapOptions);
  console.log("MAP_initialize - END");
}
function MAP_loadScript() {
  console.log("MAP_loadScript - START");
  var script = document.createElement("script");
  script.type = "text/javascript";
  script.src = "http://maps.googleapis.com/maps/api/js?key=AIzaSyCXrYix2NHdjG9LwxXIXyKQ-tQ0kgi8G2A&sensor=false&callback=MAP_initialize";
  document.body.appendChild(script);
  console.log("MAP_loadScript - END");
}
</script>

<div data-role="page" data-theme="a"> 
	 <div data-role="header">
             <h1>I'm Fucking HERE !</h1>
        </div> 
	<div data-role="content">
            <p>"Je suis la!" est un service qui vous permet en 10 secondes d'envoyer votre position par SMS à vos amis. 100% efficace, 100% gratuit !</p>
            <a href='#pageIdStep1' data-role='button' data-transition='turn'>C'est parti !</a> 
        </div> 
	<div data-role="footer">
            <h1>Copyright Ta Maman</h1>
        </div> 
</div>


<div data-role='page' id='pageIdStep1'>
    <div data-role='header'>
        <h1>I'm HERE!(1/3)</h1>
    </div>
    <div data-role='content'>
        <p>Me localiser:</p>
        <div id="idMapCanvas" width="200" height="200" style="width: 100%; height: 100%"></div>
        <a href='#' data-role='button' onClick='MAP_loadScript();'>Refresh map</a>    
        <a href='#pageIdStep2' data-role='button' data-transition='turn'>Step 2</a>    
    </div>
    <div data-role='footer'>
        <h1>Copyright Ta Maman</h1>
    </div>
</div>
<div data-role='page' id='pageIdStep2'>
    <div data-role='header'>
        <h1>I'm HERE!(2/3)</h1>
    </div>
    <div data-role='content'>
        <a href='#pageIdStep1' data-role='button' data-transition='turn' data-direction='reverse'>Step 1</a>    
        <a href='#pageIdStep3' data-role='button' data-transition='turn'>Step 3</a>
    </div>
    <div data-role='footer'>
        <h1>Copyright Ta Maman</h1>
    </div>
</div>
<div data-role='page' id='pageIdStep3'>
    <div data-role='header'>
        <h1>I'm HERE!(3/3)</h1>
    </div>
    <div data-role='content'>
        <a href='#pageIdStep2' data-role='button' data-transition='turn' data-direction='reverse'>Step 2</a>
    </div>
    <div data-role='footer'>
        <h1>Copyright Ta Maman</h1>
    </div>
</div>