<!-- <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCXrYix2NHdjG9LwxXIXyKQ-tQ0kgi8G2A&sensor=true" type="text/javascript"></script> -->
<script>
function MAP_initialize() {
    console.log("MAP_initialize - START");
  var mapOptions = {
    zoom: 8,
    center: new google.maps.LatLng(-34.397, 150.644),
    mapTypeId: google.maps.MapTypeId.ROADMAP
  }
  var map = new google.maps.Map(document.getElementById("idMapCanvas"), mapOptions);
  console.log("MAP_initialize - END");
}
/**
function MAP_loadScript() {
  console.log("MAP_loadScript - START");
  var script = document.createElement("script");
  script.type = "text/javascript";
  script.src = "http://maps.googleapis.com/maps/api/js?key=AIzaSyCXrYix2NHdjG9LwxXIXyKQ-tQ0kgi8G2A&sensor=false&callback=MAP_initialize";
  document.body.appendChild(script);
  console.log("MAP_loadScript - END");
}*/
</script>

<div data-role="page" data-theme="a"> 
	 <div data-role="header">
             <h1>I'm Fucking HERE !</h1>
        </div> 
	<div data-role="content">
            <p>"Je suis la!" est un service qui vous permet en 10 secondes d'envoyer votre position par SMS à vos amis. 100% efficace, 100% gratuit !</p>
            <hr/>
            <a href='#idPopupMap' data-rel='popup' data-position-to='window' data-role='button' >1. Localisez moi !</a>
            <a href='#' data-rel='popup' data-position-to='window' data-role='button' >2. Donnez moi un nom !</a>
            <a href='#' data-rel='popup' data-position-to='window' data-role='button' >3. Envoyez les SMS !</a>
        </div> 
	<div data-role="footer">
            <h1>Copyright Ta Maman</h1>
        </div> 
</div>
<!-- Popup for the map -->
<div data-role="popup" id="idPopupMap" data-overlay-theme="a" data-theme="d" data-tolerance="15,15" class="ui-content">
    <a href="#" data-rel="back" data-role="button" data-theme="a" data-icon="delete" data-iconpos="notext" class="ui-btn-right">Close</a>
    <iframe src="http://jesuisla.my.phpcloud.com/jesuisla/" width="480" height="320" seamless></iframe> 
</div>

<-- Popup for the event description -->
<div data-role="popup" id="idPopupDesc" data-overlay-theme="a" data-theme="d" data-tolerance="15,15" class="ui-content">

    <iframe src="http://player.vimeo.com/video/41135183" width="497" height="298" seamless></iframe>
	 
</div>

<-- Popup for the sending of SMS ->
<div data-role="popup" id="idPopupSMS" data-overlay-theme="a" data-theme="d" data-tolerance="15,15" class="ui-content">

    <iframe src="http://player.vimeo.com/video/41135183" width="497" height="298" seamless></iframe>
	 
</div>

<!--
<div data-role='page' id='pageIdStep1'>
    <div data-role='header'>
        <h1>I'm HERE!(1/3)</h1>
    </div>
    <div data-role='content'>
        <p>Me localiser:</p>
        <div id="idMapCanvas" width="200" height="200" style="width: 100%; height: 100%">
            <p>Ceci est un div.</p>
            <p>Ceci est un div.</p>
            <p>Ceci est un div.</p>
            <p>Ceci est un div.</p>
            <p>Ceci est un div.</p>
            <p>Ceci est un div.</p>
        </div>
        <a href='#' data-role='button' onClick='MAP_initialize();'>Refresh map</a>    
        <a href='#pageIdStep2' data-role='button' data-transition='turn'>Step 2</a>    
    </div>
    <div data-role='footer'>
        <h1>Copyright Ta Maman</h1>
    </div>
</div>
<div data-role='page' id='pageIdStep2'>
    <div data-role='header'>
        <h1>I'm HERE!(2/3)</h1>
    </div>
    <div data-role='content'>
        <a href='#pageIdStep1' data-role='button' data-transition='turn' data-direction='reverse'>Step 1</a>    
        <a href='#pageIdStep3' data-role='button' data-transition='turn'>Step 3</a>
    </div>
    <div data-role='footer'>
        <h1>Copyright Ta Maman</h1>
    </div>
</div>
<div data-role='page' id='pageIdStep3'>
    <div data-role='header'>
        <h1>I'm HERE!(3/3)</h1>
    </div>
    <div data-role='content'>
        <a href='#pageIdStep2' data-role='button' data-transition='turn' data-direction='reverse'>Step 2</a>
    </div>
    <div data-role='footer'>
        <h1>Copyright Ta Maman</h1>
    </div>
</div>-->