<div data-role="page" data-theme="a"> 
	 <div data-role="header">
             <h1>I'm Fucking HERE !</h1>
        </div> 
	<div data-role="content">
            <p>"Je suis la!" est un service qui vous permet en 10 secondes d'envoyer votre position par SMS à vos amis. 100% efficace, 100% gratuit !</p>
            <a href='#pageIdStep1' data-role='button' data-transition='turn'>C'est parti !</a> 
        </div> 
	<div data-role="footer">
            <h1>Copyright Ta Maman</h1>
        </div> 
</div> 
<div data-role='page' id='pageIdStep1'>
    <div data-role='header'>
        <h1>I'm Fucking HERE!(1/3)</h1>
    </div>
    <div data-role='content'>
    <a href='#pageIdStep2' data-role='button' data-transition='turn'>Step 2</a>    
    </div>
    <div data-role='footer'>
        <h1>Copyright Ta Maman</h1>
    </div>
</div>
<div data-role='page' id='pageIdStep2'>
    <div data-role='header'>
        <h1>I'm Fucking HERE!(2/3)</h1>
    </div>
    <div data-role='content'>
        <a href='#pageIdStep1' data-role='button' data-transition='turn' data-direction='reverse'>Step 1</a>    
        <a href='#pageIdStep3' data-role='button' data-transition='turn'>Step 3</a>
    </div>
    <div data-role='footer'>
        <h1>Copyright Ta Maman</h1>
    </div>
</div>
<div data-role='page' id='pageIdStep3'>
    <div data-role='header'>
        <h1>I'm Fucking HERE!(3/3)</h1>
    </div>
    <div data-role='content'>
        <a href='#pageIdStep2' data-role='button' data-transition='turn' data-direction='reverse'>Step 2</a>
    </div>
    <div data-role='footer'>
        <h1>Copyright Ta Maman</h1>
    </div>
</div>